import { useState } from "react";

export default function AddRecipeForm() {
  const [formData, setFormData] = useState({
      title: "",
          ingredients: "",
              steps: "",
                });
                  const [errors, setErrors] = useState({});

                    const validate = () => {
                        const newErrors = {};
                            if (!formData.title.trim()) newErrors.title = "⚠️ Title is required.";
                                if (!formData.ingredients.trim()) newErrors.ingredients = "⚠️ Ingredients are required.";
                                    if (!formData.steps.trim()) newErrors.steps = "⚠️ Steps are required.";
                                        return newErrors;
                                          };

                                            const handleChange = (e) => {
                                                const { name, value } = e.target;
                                                    setFormData((prev) => ({ ...prev, [name]: value }));
                                                      };

                                                        const handleSubmit = (e) => {
                                                            e.preventDefault();
                                                                const validationErrors = validate();
                                                                    if (Object.keys(validationErrors).length > 0) {
                                                                          setErrors(validationErrors);
                                                                                return;
                                                                                    }

                                                                                        alert("✅ Recipe submitted successfully!");
                                                                                            console.log("Submitted Recipe:", formData);

                                                                                                // Clear form
                                                                                                    setFormData({ title: "", ingredients: "", steps: "" });
                                                                                                        setErrors({});
                                                                                                          };

                                                                                                            return (
                                                                                                                <div className="min-h-screen flex justify-center items-center bg-gray-100 p-4 sm:p-6 md:p-8">
                                                                                                                      <form
                                                                                                                              onSubmit={handleSubmit}
                                                                                                                                      className="bg-white shadow-lg rounded-2xl p-6 sm:p-8 md:p-10 w-full max-w-lg md:max-w-2xl"
                                                                                                                                            >
                                                                                                                                                    <h1 className="text-3xl font-bold text-center text-green-600 mb-6">
                                                                                                                                                              🥗 Add New Recipe
                                                                                                                                                                      </h1>

                                                                                                                                                                              {/* Title Field */}
                                                                                                                                                                                      <div className="mb-4">
                                                                                                                                                                                                <label className="block text-gray-700 font-semibold mb-2">
                                                                                                                                                                                                            Recipe Title
                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                            type="text"
                                                                                                                                                                                                                                                        name="title"
                                                                                                                                                                                                                                                                    value={formData.title}
                                                                                                                                                                                                                                                                                onChange={handleChange}
                                                                                                                                                                                                                                                                                            className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-400"
                                                                                                                                                                                                                                                                                                        placeholder="Enter recipe title"
                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                            {errors.title && <p className="text-red-500 text-sm mt-1">{errors.title}</p>}
                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                            {/* Ingredients Field */}
                                                                                                                                                                                                                                                                                                                                                    <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                              <label className="block text-gray-700 font-semibold mb-2">
                                                                                                                                                                                                                                                                                                                                                                          Ingredients
                                                                                                                                                                                                                                                                                                                                                                                    </label>
                                                                                                                                                                                                                                                                                                                                                                                              <textarea
                                                                                                                                                                                                                                                                                                                                                                                                          name="ingredients"
                                                                                                                                                                                                                                                                                                                                                                                                                      value={formData.ingredients}
                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                              rows="4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="List ingredients separated by commas"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ></textarea>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {errors.ingredients && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-red-500 text-sm mt-1">{errors.ingredients}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Steps Field */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-gray-700 font-semibold mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Preparation Steps
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              name="steps"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={formData.steps}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  rows="5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Describe the preparation process"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ></textarea>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {errors.steps && <p className="text-red-500 text-sm mt-1">{errors.steps}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Submit Button */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full bg-green-500 text-white font-semibold py-3 rounded-lg hover:bg-green-600 transition-colors md:w-1/2 md:mx-auto md:block"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Submit Recipe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                