import { useState } from "react";

export default function AddRecipeForm() {
  const [formData, setFormData] = useState({
      title: "",
          ingredients: "",
              steps: "",
                });
                  const [error, setError] = useState("");

                    const handleChange = (e) => {
                        const { name, value } = e.target;
                            setFormData((prev) => ({ ...prev, [name]: value }));
                              };

                                const handleSubmit = (e) => {
                                    e.preventDefault();

                                        // simple validation
                                            if (!formData.title || !formData.ingredients || !formData.steps) {
                                                  setError("⚠️ Please fill out all fields before submitting.");
                                                        return;
                                                            }

                                                                alert("✅ Recipe submitted successfully!");
                                                                    console.log("Submitted Recipe:", formData);

                                                                        // clear the form
                                                                            setFormData({ title: "", ingredients: "", steps: "" });
                                                                                setError("");
                                                                                  };

                                                                                    return (
                                                                                        <div className="min-h-screen flex justify-center items-center bg-gray-100 p-6">
                                                                                              <form
                                                                                                      onSubmit={handleSubmit}
                                                                                                              className="bg-white shadow-lg rounded-2xl p-8 w-full max-w-lg"
                                                                                                                    >
                                                                                                                            <h1 className="text-3xl font-bold text-center text-green-600 mb-6">
                                                                                                                                      🥗 Add New Recipe
                                                                                                                                              </h1>

                                                                                                                                                      {error && (
                                                                                                                                                                <div className="mb-4 text-red-600 text-sm font-medium">{error}</div>
                                                                                                                                                                        )}

                                                                                                                                                                                <div className="mb-4">
                                                                                                                                                                                          <label className="block text-gray-700 font-semibold mb-2">
                                                                                                                                                                                                      Recipe Title
                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                      type="text"
                                                                                                                                                                                                                                                  name="title"
                                                                                                                                                                                                                                                              value={formData.title}
                                                                                                                                                                                                                                                                          onChange={handleChange}
                                                                                                                                                                                                                                                                                      className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-400"
                                                                                                                                                                                                                                                                                                  placeholder="Enter recipe title"
                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                            <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                      <label className="block text-gray-700 font-semibold mb-2">
                                                                                                                                                                                                                                                                                                                                                  Ingredients
                                                                                                                                                                                                                                                                                                                                                            </label>
                                                                                                                                                                                                                                                                                                                                                                      <textarea
                                                                                                                                                                                                                                                                                                                                                                                  name="ingredients"
                                                                                                                                                                                                                                                                                                                                                                                              value={formData.ingredients}
                                                                                                                                                                                                                                                                                                                                                                                                          onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                      rows="4"
                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="List ingredients separated by commas"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ></textarea>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-gray-700 font-semibold mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Preparation Steps
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              name="steps"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={formData.steps}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  rows="5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Describe the preparation process"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ></textarea>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full bg-green-600 text-white py-3 rounded-lg font-semibold hover:bg-green-700 transition duration-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Submit Recipe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              