// src/components/AdvancedSearch.jsx
import { useState } from "react";
import { searchUsers, fetchUserData } from "../services/githubService";

export default function AdvancedSearch() {
  const [term, setTerm] = useState("");
    const [location, setLocation] = useState("");
      const [minRepos, setMinRepos] = useState("");
        const [results, setResults] = useState([]);
          const [page, setPage] = useState(1);
            const [total, setTotal] = useState(0);
              const [loading, setLoading] = useState(false);
                const perPage = 30;

                  const buildQuery = () => {
                      const parts = [];
                          if (term.trim()) parts.push(term.trim());
                              if (location.trim()) parts.push(`location:${location.trim()}`);
                                  if (minRepos) parts.push(`repos:>${minRepos}`);
                                      return parts.join(" ");
                                        };

                                          async function doSearch(reset = true) {
                                              if (reset) {
                                                    setPage(1);
                                                          setResults([]);
                                                              }
                                                                  const q = buildQuery();
                                                                      if (!q) return;
                                                                          setLoading(true);
                                                                              try {
                                                                                    const data = await searchUsers(q, reset ? 1 : page, perPage);
                                                                                          if (reset) {
                                                                                                  setResults(data.items);
                                                                                                          setTotal(data.total_count);
                                                                                                                } else {
                                                                                                                        setResults((prev) => [...prev, ...data.items]);
                                                                                                                              }
                                                                                                                                  } catch (err) {
                                                                                                                                        console.error(err);
                                                                                                                                            } finally {
                                                                                                                                                  setLoading(false);
                                                                                                                                                      }
                                                                                                                                                        }

                                                                                                                                                          async function loadMore() {
                                                                                                                                                              const next = page + 1;
                                                                                                                                                                  setPage(next);
                                                                                                                                                                      setLoading(true);
                                                                                                                                                                          try {
                                                                                                                                                                                const q = buildQuery();
                                                                                                                                                                                      const data = await searchUsers(q, next, perPage);
                                                                                                                                                                                            setResults((prev) => [...prev, ...data.items]);
                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                      console.error(err);
                                                                                                                                                                                                          } finally {
                                                                                                                                                                                                                setLoading(false);
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                      }

                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                            <div className="max-w-3xl mx-auto p-4">
                                                                                                                                                                                                                                  <div className="grid grid-cols-1 sm:grid-cols-4 gap-2 mb-4">
                                                                                                                                                                                                                                          <input className="col-span-1 sm:col-span-2 px-2 py-1 border rounded" placeholder="name or term" value={term} onChange={e => setTerm(e.target.value)} />
                                                                                                                                                                                                                                                  <input className="px-2 py-1 border rounded" placeholder="location" value={location} onChange={e => setLocation(e.target.value)} />
                                                                                                                                                                                                                                                          <input className="px-2 py-1 border rounded" placeholder="min repos" value={minRepos} onChange={e => setMinRepos(e.target.value)} type="number" />
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                      <div className="flex gap-2 mb-4">
                                                                                                                                                                                                                                                                              <button onClick={() => doSearch(true)} className="px-3 py-1 border rounded">Search</button>
                                                                                                                                                                                                                                                                                      <button onClick={() => { setTerm(""); setLocation(""); setMinRepos(""); setResults([]); setTotal(0); }} className="px-3 py-1 border rounded">Clear</button>
                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                  {loading && <div>Loading...</div>}

                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                <div className="text-sm mb-2">Results: {total}</div>
                                                                                                                                                                                                                                                                                                                        <ul>
                                                                                                                                                                                                                                                                                                                                  {results.map(u => (
                                                                                                                                                                                                                                                                                                                                              <li key={u.login} className="flex items-center gap-3 mb-3">
                                                                                                                                                                                                                                                                                                                                                            <img src={u.avatar_url} alt="" width="48" height="48" className="rounded" />
                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                          <a href={u.html_url} target="_blank" rel="noreferrer" className="font-medium">{u.login}</a>
                                                                                                                                                                                                                                                                                                                                                                                                          {/* NOTE: search results don't include public_repos or location; to show them you must fetch /users/{login} */}
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </ul>

                                                                                                                                                                                                                                                                                                                                                                                                                                                              {results.length > 0 && results.length < Math.min(total, 1000) && ( // GitHub caps
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={loadMore} className="px-4 py-2 border rounded">Load more</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  