import React, { useState } from "react";
import { searchUsers } from "../services/githubService";

const Search = () => {
const [username, setUsername] = useState("");
const [location, setLocation] = useState("");
const [minRepos, setMinRepos] = useState("");
const [results, setResults] = useState([]);
          const [loading, setLoading] = useState(false);
            const [error, setError] = useState("");


 const fetchUserData = async () => {
          setLoading(true);
              setError("");
                  try {
                        const users = await searchUsers({ username, location, minRepos });
                              setResults(users);
                                  } catch (err) {
                                        setError("Failed to fetch users. Please try again.");
                                            } finally {
                                                  setLoading(false);
                                                      }
                                                        };
 }           
              const handleSearch = async (e) => {
                  e.preventDefault();
                  fetchUserData();
                      setLoading(true);
                          setError("");
                              try {
                                    const users = await searchUsers({ username, location, minRepos });
                                          setResults(users);
                                              } catch (err) {
                                                    setError("Failed to fetch users. Please try again.");
                                                        } finally {
                                                              setLoading(false);
                                                                  }
                                                                    };

                                                                      return (
                                                                          <div className="max-w-3xl mx-auto p-4">
                                                                                <h1 className="text-2xl font-bold mb-4">GitHub User Search</h1>

                                                                                      <form className="flex flex-col gap-4" onSubmit={handleSearch}>
                                                                                              <input
                                                                                                        type="text"
                                                                                                                  placeholder="Username"
                                                                                                                            value={username}
                                                                                                                                      onChange={(e) => setUsername(e.target.value)}
                                                                                                                                                className="border p-2 rounded"
                                                                                                                                                        />
                                                                                                                                                                <input
                                                                                                                                                                          type="text"
                                                                                                                                                                                    placeholder="Location"
                                                                                                                                                                                              value={location}
                                                                                                                                                                                                        onChange={(e) => setLocation(e.target.value)}
                                                                                                                                                                                                                  className="border p-2 rounded"
                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                            type="number"
                                                                                                                                                                                                                                                      placeholder="Minimum Repositories"
                                                                                                                                                                                                                                                                value={minRepos}
                                                                                                                                                                                                                                                                          onChange={(e) => setMinRepos(e.target.value)}
                                                                                                                                                                                                                                                                                    className="border p-2 rounded"
                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                              type="submit"
                                                                                                                                                                                                                                                                                                                        className="bg-blue-500 text-white p-2 rounded hover:bg-blue-600"
                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                          {loading ? "Searching..." : "Search"}
                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                        </form>

                                                                                                                                                                                                                                                                                                                                                              {error && (
                                                                                                                                                                                                                                                                                                                                                                      <p className="mt-4 text-red-500 font-semibold">{error}</p>
                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                  {/* Display results only if there are any */}
                                                                                                                                                                                                                                                                                                                                                                                        {results.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                <ul className="mt-6 space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                          {results.map((user) => (
                                                                                                                                                                                                                                                                                                                                                                                                                      <li
                                                                                                                                                                                                                                                                                                                                                                                                                                    key={user.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="border p-4 rounded flex justify-between items-center"
                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="font-bold">{user.login}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-sm">{user.location || "No location"}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-sm">Repos: {user.public_repos || "N/A"}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        href={user.html_url}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="text-blue-500 hover:underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      View Profile
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Message when no results */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {results.length === 0 && !loading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="mt-4 text-gray-500">No users found.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default Search                                                                                        